project_id = "ymbpwultwtkzdzvcrvul"

[functions.get-services]
verify_jwt = false

[functions.place-order]
verify_jwt = false

[functions.sync-order-status]
verify_jwt = false

[functions.sync-all-orders]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.send-deposit-confirmation]
verify_jwt = false

[functions.verify-deposit-code]
verify_jwt = false

[functions.korapay-webhook]
verify_jwt = false

[functions.create-user]
verify_jwt = false
